### ISSUE TITLE
[core] `Address` component that works without having to pass in provider etc

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#211]

**Comment by Ibby-devv** [comment]
I don't believe the Address component requires a provider at the moment does it?

**Comment by Dhaiwat10** [comment]
@Ibby-devv for ENS it does, I think

**Comment by hone1er** [comment]
I'm actually going to take this. But i can solve it on the component level with a different ethers method than the one currently being used.

**Comment by hone1er** [comment]
Could i change the component to require a provider instead of the RPC URL? 


I was doing some more digging around. Could we use this code for connecting to a provider in the regular component??

`const provider = new ethers.providers.Web3Provider(window.ethereum, "any");`

That way we get rid of the RPC URL currently used to connect to a provider.
