### ISSUE TITLE
Create a documentation site containing usage examples

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#251]
We need a website for the project that contains detailed documentation and guides for usage for each component and hook.  Even a basic gitbook would do for a start.

[wagmi](https://wagmi-xyz.vercel.app) is a good example that we can use as a reference. Shoutout to Rahat for suggesting this.

- [x] #252
- [x] #305 
- [ ] Migrate existing docs that we have in READMEs to the Gitbook
- [ ] Write in-depth guides and examples

**Comment by Nazeeh21** [comment]
That's a great idea.
I'd like to write the in-depth guides and examples for `web3-ui`.

**Comment by with-heart** [comment]
In light of the fact that Gitbook doesn't support dark mode, I'd like to propose that we build something custom for ourselves, because I think that'd be a good chance for us to teach some more advanced details of setting up a project with static content like this.

Happy to take the lead on this if that sounds good to yall. imo stack would be:

- Nextjs
- Chakra for styling
- `mdx` for Markdown pages with embeddable React components
- [Shiki for highlighting](https://twitter.com/souporserious/status/1478118062016516098)

**Comment by Nazeeh21** [comment]
@with-heart I agree with you. Even I'm up for this task. ☝️

**Comment by Dhaiwat10** [comment]
@with-heart I think that project would be great from the educational POV. I think we should go ahead with it for that reason.

While that project gets done, I propose using Gitbook as a temporary solution so that we have _something_ up. Does that sound good?
