### ISSUE TITLE
Where we are and how we should proceed

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#256]
Now that we are a few months in with this project, I think this is a good time to take a step back and evaluate the state of the project. In my opinion, we should think about and discuss some of the following topics:

- Are we on the right track to achieve what this project was supposed to be?
- Is this project useful for people? If not, how can we make it more useful?
- Is there anything about this project that's a deal-breaker and is stopping people from adopting it?
- Is the project in its current state too opinionated?
- Should we still move forward with the development of our own hooks when there are better fellow OSS solutions available? (wagmi, eth-hooks)
- How can we be more framework and chain agnostic? Should we be framework/chain agnostic?

**Comment by joselvelez** [comment]
Thank you for bringing this up Dhaiwat. It is a good idea to take some time at this point to assess the project's current path and determine if anything can be improved upon.

Something that has concerned me is the integration of a specific styling library. I have nothing against chakra, but I think that being opinionated about a specific styling library could turn potential users away. While I have contributed to the project, and would like to continue making contributions, I do not see myself using it - simply because my preferred styling library differs and I don't want to spend a lot of time deconstructing the built-in chakra dependencies.

Another area that has kept me confused and unable to get a full picture of is how state is being managed. If I wanted to use web3-ui in a project, it is not very clear to me where I would begin. I am a newie at web3 and that will definitely impact my challenge here, but do we not want to attract experienced and inexperienced folks to use this? Is it not being built to help folks build web3 frontends with more ease?

I think it is important that critical pieces of the project are easily understood - and global state management in my opinion is quite important. My dream scenario for web3-ui in terms of global state management would be a situation  where I install web3-ui, go into an easily identified and documented dir where global state is managed and I can drop in addition contexts and then wrap those around whatever components or other contexts I need. I have not been active in the project in about a month so it is possible that this might have changed.

I think it is a great idea to consider adopting existing hooks built by other projects if it makes sense. If that where to happen, I think there would need to be a vetting process to identify which to adopt and I am not sure if that would mean forking or adding as a dependency. There are probably areas where we do not need to re-invent the wheel and instead collaborate with other FOSS projects with similar aims.

I respect and appreciate the need to consider being framework/chain agnostic. It is probably the best way to go. It will bring in more folks and make the project more robust.

**Comment by tylerjharden** [comment]
What immediately comes to mind for me, in addition to the Chakra opinion (I've never used Chakra), is compatibility with something like Hardhay or ethers.js

Some of the core components like Providers and TokenGate seem spiritually parallel to some other Ethereum/Polygon React Boilerplate libraries, so what is the pro/con or differentiator here?

I'm building several dApps and related tooling for a couple internal and client projects, so I'd like to start contributing to a somewhat "standard" library and help champion direction towards an opinion and consensus one way or the other. 

Middleware of any kind needs to be as adaptable and design pattern oriented as possible. 

If an opinion is expressed, it must be thoroughly documented as to why. Why Chakra? Why X? Why Z? Etc. 

Definitely excited to see the work being done and hopefully I can contribute here as things progress. 

Cheers.
