### ISSUE TITLE
`@web3-ui/core@0.5.2` exports unpublished `useWriteContract` hook from `@web3-ui/hooks`

### ISSUE THREAD

**Issue by e-roy** [Developer-DAO/web3-ui#288]
I noticed when using the newer version 0.5.2 I was getting this error

![web3-ui-error](https://user-images.githubusercontent.com/70700747/152224533-60ec8803-4116-43ff-9068-141a0b0ccc3b.png)

My current solution is using `@web3-ui/core@0.5.1`

**Comment by with-heart** [comment]
After investigating, here's what happened:

- `useContract` was renamed to `useWriteContract` (#249)
	- no changeset file was created for this change
- other changes were made to `@web3-ui/core`
	- these changes included changesets targeting `@web3-ui/core`
- `changesets` opened a PR to version packages using changes from changeset files (#254)
	- this is where `@web3-ui/core@0.5.2` was published
	- since no changeset file was created for `@web3-ui/hooks`, no new version was published
- `@web3-ui/core@0.5.2` was published which uses the unpublished `useWriteContract` hook

In order to resolve this specific problem, we need to create a changeset file for the change to `@web3-ui/hooks` so that a new version will published as part of the current "Version Packages" PR (#268).

In order to avoid this problem in the future, our maintainers need to be more careful when reviewing and merging PRs to ensure that all changes to the _public API_ of our packages include a changeset.
