### ISSUE TITLE
Improve the interface of useWallet hook

### ISSUE THREAD

**Issue by emanueltimlopez** [Developer-DAO/web3-ui#67]
Its hard to know what hook exposes.

I think we can declare an interface in the provider and only provide the connection properties when connection is success.

**Comment by Dhaiwat10** [comment]
@emanueltimlopez I think we still want to keep the current `connection` API. The `connection` object being the single source of truth & reactive store is something I really like. Let me know if you have other ideas and why, though! I'm open to new ideas. 

The issue is with all those `undefined` and `null` cases. You'll often come across `context?.something` in the code which is not ideal. We want to clean that up.

**Comment by emanueltimlopez** [comment]
i undertand, i think its a lot better now
<img width="609" alt="Captura de Pantalla 2021-12-04 a la(s) 11 16 04" src="https://user-images.githubusercontent.com/25184000/144712976-25f168a4-3860-46a9-b6e5-d69addc1fe7f.png">

BTW i dont have permission to push my branch @Dhaiwat10

**Comment by etr2460** [comment]
@emanueltimlopez if you don't have write permission to the repo, you can fork it, push a branch to your fork, and then open the PR here. The contributing md mentions forking, but i'll try to reiterate it so it's clearer

**Comment by Dhaiwat10** [comment]
@emanueltimlopez I have made some changes to the `useWallet` hook via #74. Please have a look at that PR and keep those in mind!

**Comment by Dhaiwat10** [comment]
@allcontributors add @emanueltimlopez for code! <3
